# Generated by Django 6.0.6 on 2026-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('raw_salary', models.TextField(blank=True, null=True)),
                ('raw_date_posted', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
