# Generated by Django 6.0.6 on 2026-06-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobpost_currency_jobpost_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
